### ISSUE TITLE
Literally the best thing ever

### ISSUE THREAD

**Issue by kach** [bijection/nearley-playground#1]
Hey! I'm the guy who made nearley, and I just stumbled onto your work here. This is amazing!

People have been asking for something like this since the beginning of time (see issues #106, #37, #68, #142, #78 on the issue tracker…). Would it be okay if I put links to nearley-playground on nearley.js.org, and also on the README?

Thanks! (And once again, this is *so cool*.)

**Comment by bijection** [comment]
Of course! Glad you like it :)

Nearley is really awesome.

**Comment by kach** [comment]
:D I'll go do that. Meanwhile, here's something fun I made with nearley-playground:

![screen shot 2017-02-11 at 9 07 01 pm](https://cloud.githubusercontent.com/assets/5202416/22859810/109ea55c-f09e-11e6-8686-d06aeaa8e20c.png)

**Comment by bijection** [comment]
Cool!

**Comment by bijection** [comment]
Btw now you can work on multiple grammars, and tests show all possible parses.

**Comment by kach** [comment]
Nice! I like the tab interface.

One thing that might be nice is an option to download a compiled .js file, like in step (3) of the "try online" interface for the PEGjs parsing library (https://pegjs.org/online).

P.S. Meanwhile, I fixed the built-in nearley-unparse algorithm to have a "bounded" mode that doesn't run off the deep end and get into infinite loops. It takes an integer bound as input and tries to generate random strings roughly uniformly from the set of strings within that bound.

**Comment by GoMino** [comment]
+1 for the option to download a compiled .js file.

I have a weird issue with my grammar: it works fine without any ambiguity in the playground but the result is much more different using nearley-test after using nearleyc.

I would love to see how both generated javascript differ from each other.
@kach @bijection

**Comment by GoMino** [comment]
Better doing than waiting 😄 here is the pull request with the download feature! https://github.com/bijection/nearley-playground/pull/21
