### ISSUE TITLE
Case-insensitive string literals not supported

### ISSUE THREAD

**Issue by ryanking1809** [bijection/nearley-playground#15]
Would it be possible to support Case-insensitive string literals as outlined on the nearly.js website? 
`cow -> "cow"i # matches CoW, COW, and so on.`
(https://nearley.js.org/docs/grammar#more-syntax-tips-and-tricks)

When I try it the playground gives me a syntax error.

**Comment by bijection** [comment]
Fixed in a7322d721e17a33a3003f989ee9af8c3992c36ae.
