### ISSUE TITLE
Importing moo to use as a lexer

### ISSUE THREAD

**Issue by masq** [bijection/nearley-playground#16]
Hey, love the playground! Super handy for testing stuff out. However, I've gotten to the point in my grammar testing that I'd like to introduce a lexer to the code, but I'm not sure how to do that. In your examples, you use `require`, which is a node.js thing, so I don't believe it will work in the browser. Supporting that, is that when I do use require, the console reports the following error:
```
Uncaught ReferenceError: require is not defined
    at eval (eval at get_exports (tester.js?3b08:26), <anonymous>:7:16)
    at eval (eval at get_exports (tester.js?3b08:26), <anonymous>:223:3)
    at get_exports (tester.js?3b08:71)
    at Tester.render (tester.js?3b08:41)
    at eval (ReactCompositeComponent.js?063f:795)
    at measureLifeCyclePerf (ReactCompositeComponent.js?063f:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js?063f:794)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js?063f:821)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js?063f:745)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js?063f:723)
```

I've tried messing with ES6 imports a bit but can't seem to get it to work. That one yields a different error message:
```
Uncaught SyntaxError: Unexpected identifier
    at get_exports (tester.js?3b08:71)
    at Tester.render (tester.js?3b08:41)
    at eval (ReactCompositeComponent.js?063f:795)
    at measureLifeCyclePerf (ReactCompositeComponent.js?063f:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js?063f:794)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js?063f:821)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js?063f:745)
    at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js?063f:723)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js?063f:644)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js?063f:546)
```
The above is produced when using `import moo from "moo"`, `import lexer from "myLexer"` and `import lexer from "myLexer.js"` with the "myLexer.js" script in the same dir as the other default grammars such as sentence.ne and arithmetic.ne.

So that brings me to the solution the two possible solutions: 
Either the functionality to import a lexer is available, and I'm just not sure how to do it in the playground, or
import functionality is not available, and I'd like for support for it to be added in.

Though, at this point, it might be worth my time moving away from the playground for my development purposes. It was very useful for getting started! Thanks again! Let me know if I can provide any more info, etc. etc.

**Comment by bijection** [comment]
I'm glad you've been enjoying the playground! You're right that lexers are not explicitly supported, but it's possible that there's a way to get them to work. Can you post the grammar you were trying to compile / how you used the lexer?

**Comment by masq** [comment]
>Can you post the grammar you were trying to compile / how you used the lexer?

The grammar is kinda long / unrelated to the problem, so I'll post a simpler example that still gets at the core of how I was trying to use the lexer. The example is taken from the Nearley Documentation about Moo usage at https://nearley.js.org/docs/tokenizers.

```
@{%
const moo = require("moo");

const lexer = moo.compile({
  ws:     /[ \t]+/,
  number: /[0-9]+/,
  word: /[a-z]+/,
  times:  /\*|x/
});
%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number
```

This fails in the sandbox, but that's kinda expected since it's using require.

```
@{%
const mooPromise = import("moo");

const lexer = moo.compile({
  ws:     /[ \t]+/,
  number: /[0-9]+/,
  word: /[a-z]+/,
  times:  /\*|x/
});

%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number	{% _ => {console.log(mooPromise); return _;} %}
```
Also fails when trying to import moo into the given context (after installing moo via `yarn add moo` in the project directory).

Also, trying to not import Moo directly, but importing a lexer script which imports moo internally seems to have issues like so:
```
@{%

import lexer from "./lex.js";

%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number	{% _ => {console.log(lexer); return _;} %}
```
with lex.js existing at `nearley-playground/src/client/lex.js` and the contents of lex.js as the following:

```
(function() {
	const moo = require("moo");

	const lexer = moo.compile({
		ws:     /[ \t]+/,
		number: /[0-9]+/,
		word: /[a-z]+/,
		times:  /\*|x/
	});

	if (typeof module !== "undefined" && typeof module.exports !== "undefined") {
		module.exports = lexer;
	} else {
		window.lexer = lexer;
	}
})();
```

**Comment by frantic0** [comment]
@masq, I just hit this problem. Did you manage to use the Moo lexer with nearley.js in the browser?

Thanks

**Comment by bijection** [comment]
I've pushed a new version that supports referencing moo as a global variable in js inside your grammar. 

Now you should be able to do the following - let me know if it still doesn't work for you:

```javascript
@{%
	const lexer = moo.compile({
	  ws:     /[ \t]+/,
	  number: /[0-9]+/,
	  word: /[a-z]+/,
	  times:  /\*|x/
	});
%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number
```

**Comment by frantic0** [comment]
Thanks, @bijection! I was advised to use webpack to bundle up everything and it did the trick.  

Btw, very nice app, nearley-playground!

Best,
FØ

**Comment by masq** [comment]
@frantic0 I didn't at the time, just moved to working on my app more manually, which worked out fine. Glad to see you got it working since then though, @bijection! Very cool, really appreciate the work you put in :D
