### ISSUE TITLE
Consider support use Moo at playground?

### ISSUE THREAD

**Issue by sputnikW** [bijection/nearley-playground#36]
Consider support use Moo at playground?

moo is the recommend tokenizer of nearley. so maybe it's required by users frequently.

**Comment by bijection** [comment]
Hey sputnik, moo has been supported as a global, but you can now use it with `require` as well, as of https://github.com/bijection/nearley-playground/commit/f3023eb1ed1ecf24dd0f6eb62cfdd61d7c52c592.

See https://github.com/bijection/nearley-playground/commit/644064c5f70bb3483de332632c7053fe39a11f5e for an example. Hope that helps!
