### ISSUE TITLE
Freezes when (accidentally) importing the same builtin multiple times

### ISSUE THREAD

**Issue by mickdekkers** [bijection/nearley-playground#9]
Example:
```nearley
@builtin "string.ne"
@builtin "string.ne"

main -> dqstring
```

I duplicated the string import line, intending to replace "string.ne" with "number.ne".
Unfortunately the editor froze, but thanks to [this comment](https://github.com/bijection/nearley-playground/issues/3#issuecomment-289290431) I was able to retrieve my changes through localstorage.

**Comment by bijection** [comment]
Fixed, only a year later!

**Comment by mickdekkers** [comment]
Much appreciated regardless 😄
